version: '3.8'

services:
  emotion-chatbot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DEBUG=False
    env_file:
      - .env
    volumes:
      # 일기 파일 저장을 위한 볼륨
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 선택적: nginx 리버스 프록시 (운영 환경용)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - emotion-chatbot
    restart: unless-stopped
    profiles:
      - production

volumes:
  data:
    driver: local